services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn flight_optimizer.app:app --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - "8000:8000"
  frontend: 
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "5000:80"